---
title: "Capstone"
author: "Chris Lattanzio"
date: "9/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

#install.packages("bigrquery")
#install.packages('devtools') 
#devtools::install_github("rstats-db/bigrquery")


library('bigrquery')
library('tidyverse')
```

```{r}

# install.packages('devtools') devtools::install_github("rstats-db/bigrquery")
# Use your project ID here
project <- "capstone-247602" # put your project ID here
# Example query - select copies of files with content containing "TODO"
sql <- "SELECT * FROM [combined_digital_linear.tbl_Joined_By_Series_Name_And_AirDate]"
# Execute the query and store the result
joined_data <- query_exec(sql, project = project, useLegacySql = FALSE)


```

```{r}

This_Is_Us <- subset(joined_data, joined_data$series == 'THIS IS US')


```


```{r}
 
Tdata.train <-  This_Is_Us[sample(1:nrow(This_Is_Us), 1000,  replace=FALSE),]

Tdata.eval <- This_Is_Us[sample(1000:nrow(This_Is_Us), 1000,  replace=FALSE),]

Tform <- as.formula(average_length ~.)  # the formula to be used in models

library(performanceEstimation)
library(e1071)
exp <- performanceEstimation(
    PredTask(Tform, Tdata.train, 'THIS IS US'),   
    c(workflowVariants('timeseriesWF',wfID="svm", # creates a sliding or growing timeseries window
               type="slide", relearn.step=90,
               learner='svm',learner.pars=list(cost=c(1,5,10),gamma=c(0.001, 0.01, 0.1), epsilon=c(0.1,0.05)) ),
      workflowVariants('timeseriesWF', wfID="nnet", # creates a sliding or growing timeseries window
               type="slide", relearn.step=90, # 90 days slide
               learner='nnet', learner.pars=list(size = c(1,5,10), decay = c(0.001, 0.01, 0.1) 
                                                 , maxit = 1000, linout = TRUE, trace = FALSE )), 
     Workflow('timeseriesWF', wfID="randomForest", # creates a sliding or growing timeseries window
               type="slide", relearn.step=90, learner='randomForest')
      ),
    EstimationTask(metrics=c("theil","mae","mse", "rmse"), # Close to zero as possible.  Estimate of errors to base line (previous model)
                   method=MonteCarlo(nReps=10,szTrain=0.5,szTest=0.25)))



## ----size="tiny",cache=FALSE---------------------------------------------
summary(exp)   

## ----size="scriptsize",fig.width=8,fig.height=8,out.width="0.5\\textwidth",cache=FALSE----
plot(exp)   



```
